### ISSUE TITLE
Problem with signing in

### ISSUE THREAD

**Issue by stmblfrcr** [doctorrokter/basket#1]
Hi, thanks for this app. Unfortunately when trying to sign in, it throws an error message: "This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit". I guess you have to allow more users on the Dropbox developer site and/or even apply for production. Best regards.

**Comment by doctorrokter** [comment]
Hi! 
Thanks for choosing Basket and posting an issue here. It was my fault: I didn't switched Dropbox from dev to prod environment through Dropbox App Console.

No I fixed it, you can try again. If app won't work with already obtained token, please, do all steps again and obtain a new token.

**Comment by stmblfrcr** [comment]
Thank you! Much appreciated.
