### ISSUE TITLE
Thumbnails showing wrong files

### ISSUE THREAD

**Issue by imaginaryenemy** [doctorrokter/basket#2]
When more files are 'loaded' the thumbnails are not rendered appropriately. An error message is given stating there was an error loading the thumbnails because of 'unsupported extension'. The result is the wrong thumbnail showing for the files (including folder icons).

**Comment by doctorrokter** [comment]
Hi! 
Good catch! Will fix in next release ASAP.

**Comment by imaginaryenemy** [comment]
I just installed 1.0.1, and the issue persists.  The error no longer shows, but the thumbnails still get attributed to the wrong files after loading more content.  The folder icons seem to be free from the issue now.  I installed in directly on top of the BBW version.  I don't know if that could be causing issues or not.

**Comment by doctorrokter** [comment]
Hi! 
Try a new release 1.0.2. On my device it finally works as expected.

**Comment by imaginaryenemy** [comment]
Perfect! Bug squashed! Thanks!
