### ISSUE TITLE
Pictures fail to upload using 'Share to Basket' function

### ISSUE THREAD

**Issue by imaginaryenemy** [doctorrokter/basket#4]
When sharing a photo to Basket using Share function two successful upload notifications are given (two 'toast' notifications, but only one in the hub), but the pictures never show up. Uploading a photo directly from Basket uploads the photo without issue.

**Comment by doctorrokter** [comment]
Hi!

I can't reproduce this issue at that moment. Tried to "share" 2-10 different files (images and even video and music) and all works as expected, thumbnails loaded for images ok (except gifs, which is not supported), video/audio plays Ok. 
Also, when you share files with Basket and app invoked as Card there shouldn't be any toast notifications, app closes momentically after you tap "Upload", notifications should be only in hub: first - before upload where will be listed files for uploading, and secod - after upload has been finished.

**Comment by doctorrokter** [comment]
Check your app version. Latest is 1.1.0.647

**Comment by imaginaryenemy** [comment]
That is the version I am using. Here is a video of me trying. Turns out the double toasts were 'uploading' and 'uploaded', but the file was so small I couldn't tell the difference in message. This picture is larger, so they are spaced out.

https://www.dropbox.com/s/f2y6umwnilgak9i/VID_20180110_072205-20180110_073508-MMT.mp4?dl=0

**Comment by doctorrokter** [comment]
See. That's weird. I tried now on several devices without problems, the file size doesn't matter. 
Can you completely delete an app, reinstall from scratch and try again?

**Comment by imaginaryenemy** [comment]
That did it! So sorry for the false alarm.

**Comment by doctorrokter** [comment]
Yay! Cool!

**Comment by doctorrokter** [comment]
Hi!

You were right :)

I found the reason of problem above. It was a minor bug with headless part, which doesn't obtained access_token on device reload or after app updates.

Version 1.1.1 fixes it!

**Comment by imaginaryenemy** [comment]
Good catch!
